name: Package and push image
on:
  workflow_dispatch:
    inputs:
      push_image:
        type: boolean
        default: false
        description: "Push image to repo?"
      deploy:
        type: boolean
        default: false
        description: "Deploy to k8s?"

jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tagSetup.outputs.tag }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: |
          mvn clean package

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: helloWorld
          path: target/*.jar

  Push:
    if: ${{ inputs.push_image == true}}
    runs-on: ubuntu-latest
    needs: Build

    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Set image tag
        id: tag_setup
        run: |
          branch=${GITHUB_REF##*/}
          if [branch = main]; then
            "tag=latest" >> $GITHUB_ENV
          else
            echo "tag=$branch" >> $GITHUB_ENV
          fi

      - name: Login GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Download .jar
        uses: actions/download-artifact@v4
        with:
          name: helloWorld
          path: target

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner}}/helloworld-${{ env.tag }} .

      - name: Push Docker image
        run: |
          docker image push ghcr.io/${{ github.repository_owner}}/helloworld-${{ env.tag }}

  Deploy:
    if: ${{ inputs.deploy == true}}
    needs: Push
    uses: .github/workflows/login-cluster.yml

