name: Package and push image
run-name: Package and push image
on:
  workflow_dispatch:
    inputs:
      push_image:
        type: boolean
        default: false
        description: "Push image to repo?"

jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tagSetup.outputs.tag }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: |
          mvn clean package

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: helloWorld
          path: target/*.jar

      - name: Set image tag
        id: tagSetup
        run: |
          branch=${GITHUB_REF##*/}
          echo 'Branch name: $branch'